Update platform to qemu for all targets
unikraft/app-helloworld-cpp pull request #13
Opened 2023-07-01 10:26 UTC by gabrielmocanu

Update targets to qemu and modify the order for all libraries.

2023-07-01 11:31 UTC, craciunoiuc approved these changes
All good here. Thanks!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

2023-07-01 14:10 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-07-03 13:44 UTC, nderjung requested changes
See inline

2023-07-03 13:44 UTC, nderjung commented on kraft.yaml
> +    platform: firecraker
```diff
- platform: firecracker
+ platform: fc
```

2023-07-25 21:08 UTC, razvand commented
@nderjung , what needs to happen here? Use `fc` instead of `firecracker`?

2023-07-30 13:59 UTC, gabrielmocanu commented
> @nderjung , what needs to happen here? Use `fc` instead of `firecracker`?

Both are accepted, you can see this [here](https://github.com/unikraft/kraftkit/blob/57e76ddf6376f40e1f541e95fe9f6a9c12059c1c/unikraft/plat/platform.go#L96).

2023-08-06 07:42 UTC, razvand approved these changes
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-08-07 15:46 UTC, closed without merging