Add configuration and scripts
unikraft/app-helloworld-cpp pull request #16
Opened 2023-08-06 09:08 UTC by razvand

Add Make-based setup files.

2023-08-06 17:47 UTC, RaduNichita requested changes
All good with me besides that one small comment. Thanks @razvand

2023-08-06 17:47 UTC, RaduNichita commented on README.md
> +git clone https://github.com/unikraft/app-helloworld-cpp helloworld-cpp
I think we need to separate the common commands (the ones with cloning the repos) from the one specific to platform / architectures.

2023-08-06 18:12 UTC, razvand commented on README.md
> +git clone https://github.com/unikraft/app-helloworld-cpp helloworld-cpp
I see your point. But, currently, this is how we did for all repositories. I would keep it like this, and, if we think it's a good idea, we will update it all over the place.

2023-08-06 18:27 UTC, RaduNichita commented on README.md
> +git clone https://github.com/unikraft/app-helloworld-cpp helloworld-cpp
Ok, fair point. Then let's merge like it is.

2023-08-06 18:27 UTC, RaduNichita approved these changes
All good. Thanks @razvand 

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

2023-08-06 19:19 UTC, StefanJum requested changes
See the comments.

2023-08-06 19:19 UTC, StefanJum commented on README.md
> +Use the `.config.helloworld-cpp-qemu-arm64` configuration file together with `make defconfig` to create the configuration file:
```suggestion
Use the `.config.helloworld-cpp-qemu-aarch64` configuration file together with `make defconfig` to create the configuration file:
```

2023-08-06 19:19 UTC, StefanJum commented on README.md
> +UK_DEFCONFIG=$(pwd)/.config.helloworld-cpp-qemu-arm64 make defconfig
```suggestion
UK_DEFCONFIG=$(pwd)/.config.helloworld-cpp-qemu-aarch64 make defconfig
```

2023-08-06 19:19 UTC, StefanJum commented on README.md
> +     .config.helloworld-cpp-fc-x86_64  .config.helloworld-cpp-qemu-arm64  .config.helloworld-cpp-qemu-x86_64  helloworld-cpp-fc-x86_64.json  kraft.yaml  Makefile  Makefile.uk  README.md [...]
```suggestion
     .config.helloworld-cpp-fc-x86_64  .config.helloworld-cpp-qemu-aarch64  .config.helloworld-cpp-qemu-x86_64  helloworld-cpp-fc-x86_64.json  kraft.yaml  Makefile  Makefile.uk  README.md [...]
```

2023-08-07 03:42 UTC, razvand commented
@StefanJum, fixed.

2023-08-07 06:11 UTC, StefanJum approved these changes
All good, I'll add the tag after #13 is merged and this is rebased.

2023-08-10 18:31 UTC, StefanJum approved these changes
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-08-10 22:09 UTC, RaduNichita approved these changes
All good with rebase. Thanks, @razvand! 

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

2023-08-10 22:18 UTC, closed without merging